Dra 422 ready for stage
kb-dk/ds-datahandler pull request #60
Opened 2024-04-18 11:03 UTC by VictorHarbo

2024-04-18 12:55 UTC, tokee requested changes
Slight error in the Solr update URL.

2024-04-18 12:55 UTC, tokee commented on conf/ds-datahandler-environment.yaml.SAMPLE
> +  updateUrl:  http://localhost:10011/solr/ds/update
` http://localhost:10011/solr/ds-write/update`

2024-04-18 16:17 UTC, VictorHarbo commented on conf/ds-datahandler-environment.yaml.SAMPLE
> +  updateUrl:  http://localhost:10011/solr/ds/update
nice catch!

2024-04-19 13:05 UTC, tokee approved these changes

2024-04-19 13:05 UTC, merged