Dra 710 make kaltura xml from solr
kb-dk/ds-datahandler pull request #88
Opened 2024-09-24 09:23 UTC by thomasegense

Addd manual batch job to create bulk upload XML for Kaltura from solr documents json. There are 3 cases for how to create the ftp download.
bart-tv
bart-radio
kuana/preservica (here extension .mp3 or .mp4 must be added)

2024-09-24 11:55 UTC, VictorHarbo requested changes
Some suggestions

2024-09-24 12:03 UTC, thomasegense commented on src/test/java/dk/kb/datahandler/kaltura/GenerateKalturaUploadXmlFromSolrDocs.java
> +    private static String generateKuanaTVDownloadUrl(String fileId,String resourceType) {
Agree! Fixed

2024-09-25 06:15 UTC, thomasegense commented on src/test/java/dk/kb/datahandler/kaltura/GenerateKalturaUploadXmlFromSolrDocs.java
> +    final static String FTP_BART_RADIO_PATH="https://deic-download.kb.dk/kuana-store/bart-access-copies-radio/";
Allowed only by DEIC IP

2024-09-25 07:24 UTC, VictorHarbo commented on src/test/java/dk/kb/datahandler/kaltura/GenerateKalturaUploadXmlFromSolrDocs.java
> +    final static String TAG3="test"; //Asger used this on kaltura-STAGE. Dont know what to use for PROD.
This looks good now

2024-09-25 08:13 UTC, VictorHarbo requested changes
Two small things which I believe you might just have overseen.

2024-09-25 08:13 UTC, VictorHarbo commented on src/test/java/dk/kb/datahandler/kaltura/GenerateKalturaUploadXmlFromSolrDocs.java
> + * The solr json document can be produced with this query: holdback_expired_date:[NOW TO *]
Please update the solr query here in the written documentation as well.

2024-09-25 08:13 UTC, VictorHarbo commented on src/test/java/dk/kb/datahandler/kaltura/GenerateKalturaUploadXmlFromSolrDocs.java
> +    private static String generateKuanaTVDownloadUrl(String fileId,String resourceType) {
This still has TV in the method name.

2024-09-25 08:48 UTC, VictorHarbo approved these changes
Looks good now!

2024-09-25 08:48 UTC, merged